
halyard:
  gitops:
    enabled: true
    secretName: opsmx-gitops-auth
    repo:
      type: git # git, bitbucket-stash or S3, please use another template for github/stash
      baseUrlHostName: github.com    # Specify the Base FQDN of your repository without the protocol
      organization: ShekinahDadala
      repository: test-oss # repo name for GitOps Halyard (Sample Reference: https://github.com/OpsMx/sample-gitops-repo.git).
      halConfigBranch: main # Branch under which halyard config is present under above repository
      halConfigPath: / #relative path from repository root folder
      dynamicAccRepository: test-oss # Please provide the repo name of the GitOps Dynamic Accounts Directory. Can be same as Hal repo.
      dynAccntConfigPath: / #relative path from repository root folder
      username: ShekinahDadala  # Username to authenticate with git/stash repo
      token: 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
  # If spinnakerVersion is not specified appVersion in Chart.yml is chosen for Spinnaker
  spinnakerVersion: 1.30.1
  image:
    repository: us-docker.pkg.dev/spinnaker-community/docker/halyard
    tag: 1.45.0
